name: Build and Upload Slides

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: slides  # Set the default working directory to 'slides/'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Ensure pdf directory exists
        run: mkdir -p ./pdf      
      
      - name: Build slides
        run: make CMake.pdf

      - name: Upload slides PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CMake-slides
          path: slides/pdf/CMake.pdf

